increased compatibility with python 3
File "/zope4/lib/python3.7/site-packages/Products/ZPsycopgDA/db.py", line 204
    except StandardError, err:
                        ^
SyntaxError: invalid syntax

Just change to "as", since it works in both python2.7 and python3